services:
  conqueco:
    image: conqueco
    container_name: conqueco
    build:
      context: .
      dockerfile: Conqueco/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${CONNECTION_STRING}
      Jwt__Key: ${JWT__Key}
      Jwt__Issuer: ${JWT__Issuer}
      Jwt__Audience: ${JWT__Audience}
      Jwt__DurationInMinutes: ${JWT__DurationInMinutes}
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:17
    container_name: conqueco-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: conqueco-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data: